#------------------------------------------------------------------------------
# CSE120 hw5
# Group members: Yufan Zhu, James Li
# Makefile:
#    % Usage:
#       make                   -- generates executable files
#       make clean             -- clean up executable files
#------------------------------------------------------------------------------

matmul : matmul.c
	gcc -o matmul matmul.c

clean :
	rm -f matmul a.out
